// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#ifndef _KNOBOS_UI_H
#define _KNOBOS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_FlashScreen
void ui_FlashScreen_screen_init(void);
extern lv_obj_t * ui_FlashScreen;
extern lv_obj_t * ui_logo;
extern lv_obj_t * ui_knobosLabel;
extern lv_obj_t * ui_firmwareLabel;
void ui_event_roundButton_roundButton(lv_event_t * e);
extern lv_obj_t * ui_roundButton;
// SCREEN: ui_Changelog
void ui_Changelog_screen_init(void);
void ui_event_Changelog(lv_event_t * e);
extern lv_obj_t * ui_Changelog;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
// SCREEN: ui_HomeScreen
void ui_HomeScreen_screen_init(void);
void ui_event_HomeScreen(lv_event_t * e);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_TimePanel;
extern lv_obj_t * ui_Hour;
extern lv_obj_t * ui_Mins;
extern lv_obj_t * ui_DateInfo;
extern lv_obj_t * ui_StatusPanel;
extern lv_obj_t * ui_WifiPanel;
extern lv_obj_t * ui_WifiImage;
extern lv_obj_t * ui_ProfilePanel;
extern lv_obj_t * ui_ProfileImage;
extern lv_obj_t * ui_SettingsPanel;
extern lv_obj_t * ui_SettingsImage;
// SCREEN: ui_AppScreenDisplay
void ui_AppScreenDisplay_screen_init(void);
void ui_event_AppScreenDisplay(lv_event_t * e);
extern lv_obj_t * ui_AppScreenDisplay;
extern lv_obj_t * ui_AppScreen;
void ui_event_AppComponent2(lv_event_t * e);
extern lv_obj_t * ui_AppComponent2;
extern lv_obj_t * ui_AppImage1;
extern lv_obj_t * ui_AppLabel1;
extern lv_obj_t * ui_AppComponent3;
extern lv_obj_t * ui_AppImage4;
extern lv_obj_t * ui_AppLabel4;
extern lv_obj_t * ui_AppComponent4;
extern lv_obj_t * ui_AppImage3;
extern lv_obj_t * ui_AppLabel3;
void ui_event_Panel2(lv_event_t * e);
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_LightControl
void ui_LightControl_screen_init(void);
void ui_event_LightControl(lv_event_t * e);
extern lv_obj_t * ui_LightControl;
extern lv_obj_t * ui_AppTitleComp1;
extern lv_obj_t * ui_AppControls;
extern lv_obj_t * ui_SwitchHolder;
extern lv_obj_t * ui_switch;
extern lv_obj_t * ui_SwitchLabel;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label1;
void ui_event_ChangeColorButton(lv_event_t * e);
extern lv_obj_t * ui_ChangeColorButton;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_LightColorScreen
void ui_LightColorScreen_screen_init(void);
void ui_event_LightColorScreen(lv_event_t * e);
extern lv_obj_t * ui_LightColorScreen;
extern lv_obj_t * ui_LightColorWheel;
extern lv_obj_t * ui_SetColorButton;
extern lv_obj_t * ui_SetColorLabel;
// SCREEN: ui_FanControl
void ui_FanControl_screen_init(void);
void ui_event_FanControl(lv_event_t * e);
extern lv_obj_t * ui_FanControl;
extern lv_obj_t * ui_AppTitleComp2;
extern lv_obj_t * ui_AppControls1;
extern lv_obj_t * ui_SwitchHolder1;
extern lv_obj_t * ui_switch1;
extern lv_obj_t * ui_SwitchLabel1;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label6;
void ui_event_ChangeColorButton1(lv_event_t * e);
extern lv_obj_t * ui_ChangeColorButton1;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1828568161);    // assets\knob (6).png
LV_IMG_DECLARE(ui_img_1656806725);    // assets\no-wifi.png
LV_IMG_DECLARE(ui_img_suitcase_png);    // assets\suitcase.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets\settings.png
LV_IMG_DECLARE(ui_img_lightbulb_png);    // assets\lightbulb.png
LV_IMG_DECLARE(ui_img_fan_png);    // assets\fan.png
LV_IMG_DECLARE(ui_img_laptop_png);    // assets\laptop.png



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
