// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "ui.h"

void swithOnFunction(lv_event_t * e)
{

}

void brightnessLevelChange(lv_event_t * e)
{
	
}

void checkLightStatus(lv_event_t * e)
{
	// Your code here
}
