// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_FlashScreen_screen_init(void)
{
    ui_FlashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FlashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_FlashScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FlashScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FlashScreen, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_FlashScreen);
    lv_obj_set_width(ui_Panel1, 147);
    lv_obj_set_height(ui_Panel1, 141);
    lv_obj_set_x(ui_Panel1, -36);
    lv_obj_set_y(ui_Panel1, -56);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Panel1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Panel1);
    lv_img_set_src(ui_Image3, &ui_img_group_1_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 241
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 332
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image3, 100);
    lv_obj_set_style_bg_color(ui_Image3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Image3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roundButton = ui_roundButton_create(ui_FlashScreen);
    lv_obj_set_x(ui_roundButton, 0);
    lv_obj_set_y(ui_roundButton, 88);
    lv_obj_add_state(ui_roundButton, LV_STATE_PRESSED);       /// States
    lv_obj_set_style_bg_color(ui_roundButton, lv_color_hex(0x65D7ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_roundButton, lv_color_hex(0x69DDEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_roundButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_roundButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roundButton, lv_color_hex(0x2541BC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);


    lv_obj_add_event_cb(ui_roundButton, ui_event_roundButton_roundButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FlashScreen, ui_event_FlashScreen, LV_EVENT_ALL, NULL);

}
