// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_FlashScreen_screen_init(void)
{
    ui_FlashScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_FlashScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_FlashScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_FlashScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FlashScreen, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_logo = lv_img_create(ui_FlashScreen);
    lv_img_set_src(ui_logo, &ui_img_1828568161);
    lv_obj_set_width(ui_logo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_logo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_logo, 0);
    lv_obj_set_y(ui_logo, -41);
    lv_obj_set_align(ui_logo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_logo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_knobosLabel = lv_label_create(ui_FlashScreen);
    lv_obj_set_width(ui_knobosLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_knobosLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_knobosLabel, 0);
    lv_obj_set_y(ui_knobosLabel, 21);
    lv_obj_set_align(ui_knobosLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_knobosLabel, "KnobOS");
    lv_obj_set_style_text_color(ui_knobosLabel, lv_color_hex(0x2F6CDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_knobosLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_knobosLabel, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_firmwareLabel = lv_label_create(ui_FlashScreen);
    lv_obj_set_width(ui_firmwareLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_firmwareLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_firmwareLabel, 0);
    lv_obj_set_y(ui_firmwareLabel, 49);
    lv_obj_set_align(ui_firmwareLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_firmwareLabel, "Firmware Version: 0.0.2");
    lv_obj_set_style_text_color(ui_firmwareLabel, lv_color_hex(0x2644BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_firmwareLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_roundButton = ui_roundButton_create(ui_FlashScreen);
    lv_obj_set_x(ui_roundButton, 0);
    lv_obj_set_y(ui_roundButton, 88);
    lv_obj_add_state(ui_roundButton, LV_STATE_PRESSED);       /// States
    lv_obj_set_style_bg_color(ui_roundButton, lv_color_hex(0x65D7ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_roundButton, lv_color_hex(0x69DDEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_roundButton, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_roundButton, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_roundButton, lv_color_hex(0x2541BC), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_roundButton, 255, LV_PART_MAIN | LV_STATE_PRESSED);


    lv_obj_add_event_cb(ui_roundButton, ui_event_roundButton_roundButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FlashScreen, ui_event_FlashScreen, LV_EVENT_ALL, NULL);

}
