// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimePanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_TimePanel, 119);
    lv_obj_set_height(ui_TimePanel, 140);
    lv_obj_set_x(ui_TimePanel, -26);
    lv_obj_set_y(ui_TimePanel, -5);
    lv_obj_set_align(ui_TimePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TimePanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TimePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Hour = lv_label_create(ui_TimePanel);
    lv_obj_set_width(ui_Hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Hour, -18);
    lv_obj_set_y(ui_Hour, -28);
    lv_obj_set_align(ui_Hour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Hour, "02");
    lv_obj_set_style_text_color(ui_Hour, lv_color_hex(0x2040BD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Hour, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Mins = lv_label_create(ui_TimePanel);
    lv_obj_set_width(ui_Mins, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mins, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mins, -21);
    lv_obj_set_y(ui_Mins, 13);
    lv_obj_set_align(ui_Mins, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mins, "59");
    lv_obj_set_style_text_color(ui_Mins, lv_color_hex(0x66D8ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Mins, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Mins, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateInfo = lv_label_create(ui_TimePanel);
    lv_obj_set_width(ui_DateInfo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DateInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DateInfo, -51);
    lv_obj_set_y(ui_DateInfo, 24);
    lv_obj_set_align(ui_DateInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DateInfo, "07-02-2024");
    lv_obj_set_style_text_color(ui_DateInfo, lv_color_hex(0x2544BE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DateInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusPanel = lv_obj_create(ui_HomeScreen);
    lv_obj_set_width(ui_StatusPanel, 47);
    lv_obj_set_height(ui_StatusPanel, 140);
    lv_obj_set_x(ui_StatusPanel, 64);
    lv_obj_set_y(ui_StatusPanel, -4);
    lv_obj_set_align(ui_StatusPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StatusPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StatusPanel, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StatusPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiPanel = lv_obj_create(ui_StatusPanel);
    lv_obj_set_width(ui_WifiPanel, 37);
    lv_obj_set_height(ui_WifiPanel, 37);
    lv_obj_set_x(ui_WifiPanel, 65);
    lv_obj_set_y(ui_WifiPanel, -45);
    lv_obj_set_align(ui_WifiPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WifiPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_WifiPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WifiPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiImage = lv_img_create(ui_WifiPanel);
    lv_img_set_src(ui_WifiImage, &ui_img_nowifi_png);
    lv_obj_set_width(ui_WifiImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiImage, 60);
    lv_obj_set_y(ui_WifiImage, -38);
    lv_obj_set_align(ui_WifiImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WifiImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WifiImage, 100);

    ui_ProfilePanel = lv_obj_create(ui_StatusPanel);
    lv_obj_set_width(ui_ProfilePanel, 37);
    lv_obj_set_height(ui_ProfilePanel, 37);
    lv_obj_set_x(ui_ProfilePanel, 65);
    lv_obj_set_y(ui_ProfilePanel, -45);
    lv_obj_set_align(ui_ProfilePanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ProfilePanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ProfilePanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ProfilePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ProfileImage = lv_img_create(ui_ProfilePanel);
    lv_img_set_src(ui_ProfileImage, &ui_img_suitcase_png);
    lv_obj_set_width(ui_ProfileImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ProfileImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ProfileImage, 60);
    lv_obj_set_y(ui_ProfileImage, -38);
    lv_obj_set_align(ui_ProfileImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ProfileImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ProfileImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ProfileImage, 100);

    ui_SettingsPanel = lv_obj_create(ui_StatusPanel);
    lv_obj_set_width(ui_SettingsPanel, 37);
    lv_obj_set_height(ui_SettingsPanel, 37);
    lv_obj_set_x(ui_SettingsPanel, 65);
    lv_obj_set_y(ui_SettingsPanel, -45);
    lv_obj_set_align(ui_SettingsPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsImage = lv_img_create(ui_SettingsPanel);
    lv_img_set_src(ui_SettingsImage, &ui_img_settings_png);
    lv_obj_set_width(ui_SettingsImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsImage, 60);
    lv_obj_set_y(ui_SettingsImage, -38);
    lv_obj_set_align(ui_SettingsImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SettingsImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_SettingsImage, 100);

    lv_obj_add_event_cb(ui_SettingsPanel, ui_event_SettingsPanel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HomeScreen, ui_event_HomeScreen, LV_EVENT_ALL, NULL);

}
