// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_LaptopControl_screen_init(void)
{
    ui_LaptopControl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LaptopControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_LaptopControl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LaptopControl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_obj_set_style_pad_left(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_AppTitleComp1 = ui_AppTitleComp_create(ui_LaptopControl);
    lv_obj_set_x(ui_AppTitleComp1, 0);
    lv_obj_set_y(ui_AppTitleComp1, -82);
    lv_obj_set_flex_flow(ui_AppTitleComp1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AppTitleComp1, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);


    lv_label_set_text(ui_comp_get_child(ui_AppTitleComp1, UI_COMP_APPTITLECOMP_APPLABEL2), "Lap Control");

    ui_AppControls = lv_obj_create(ui_LaptopControl);
    lv_obj_set_width(ui_AppControls, 189);
    lv_obj_set_height(ui_AppControls, 113);
    lv_obj_set_x(ui_AppControls, -1);
    lv_obj_set_y(ui_AppControls, -36);
    lv_obj_set_align(ui_AppControls, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AppControls, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AppControls, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppControls, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchHolder = lv_obj_create(ui_AppControls);
    lv_obj_set_width(ui_SwitchHolder, 175);
    lv_obj_set_height(ui_SwitchHolder, 31);
    lv_obj_set_x(ui_SwitchHolder, -1);
    lv_obj_set_y(ui_SwitchHolder, -35);
    lv_obj_set_align(ui_SwitchHolder, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SwitchHolder, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SwitchHolder, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SwitchHolder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SwitchHolder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SwitchHolder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_SwitchHolder, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_SwitchHolder, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch = lv_switch_create(ui_SwitchHolder);
    lv_obj_set_width(ui_switch, 50);
    lv_obj_set_height(ui_switch, 25);
    lv_obj_set_x(ui_switch, -62);
    lv_obj_set_y(ui_switch, -19);
    lv_obj_set_align(ui_switch, LV_ALIGN_CENTER);


    ui_SwitchLabel = lv_label_create(ui_SwitchHolder);
    lv_obj_set_width(ui_SwitchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SwitchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SwitchLabel, 14);
    lv_obj_set_y(ui_SwitchLabel, -5);
    lv_obj_set_align(ui_SwitchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SwitchLabel, "Switch On");

    ui_Slider1 = lv_slider_create(ui_AppControls);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 1);
    lv_obj_set_y(ui_Slider1, 7);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);


    ui_Label1 = lv_label_create(ui_AppControls);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 4);
    lv_obj_set_y(ui_Label1, 34);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Brightness Level");

    lv_obj_add_event_cb(ui_LaptopControl, ui_event_LaptopControl, LV_EVENT_ALL, NULL);

}
