// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_LightColorScreen_screen_init(void)
{
    ui_LightColorScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LightColorScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_LightColorScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LightColorScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);

    ui_LightColorWheel = lv_colorwheel_create(ui_LightColorScreen, true);
    lv_obj_set_width(ui_LightColorWheel, 180);
    lv_obj_set_height(ui_LightColorWheel, 180);
    lv_obj_set_x(ui_LightColorWheel, -2);
    lv_obj_set_y(ui_LightColorWheel, 0);
    lv_obj_set_align(ui_LightColorWheel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LightColorWheel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LightColorWheel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_SetColorButton = lv_btn_create(ui_LightColorWheel);
    lv_obj_set_width(ui_SetColorButton, 100);
    lv_obj_set_height(ui_SetColorButton, 50);
    lv_obj_set_x(ui_SetColorButton, -499);
    lv_obj_set_y(ui_SetColorButton, -130);
    lv_obj_set_align(ui_SetColorButton, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SetColorButton, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SetColorButton, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetColorButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetColorButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SetColorLabel = lv_label_create(ui_SetColorButton);
    lv_obj_set_width(ui_SetColorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetColorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetColorLabel, -28);
    lv_obj_set_y(ui_SetColorLabel, -9);
    lv_obj_set_align(ui_SetColorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetColorLabel, "Set Color");

    lv_obj_add_event_cb(ui_LightColorScreen, ui_event_LightColorScreen, LV_EVENT_ALL, NULL);

}
