// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_LaptopControl_screen_init(void)
{
    ui_LaptopControl = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LaptopControl, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_LaptopControl, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_LaptopControl, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_obj_set_style_pad_left(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_LaptopControl, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_AppTitleComp4 = ui_AppTitleComp_create(ui_LaptopControl);
    lv_obj_set_width(ui_AppTitleComp4, 159);
    lv_obj_set_height(ui_AppTitleComp4, 31);
    lv_obj_set_x(ui_AppTitleComp4, 0);
    lv_obj_set_y(ui_AppTitleComp4, -82);
    lv_obj_set_flex_flow(ui_AppTitleComp4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AppTitleComp4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_img_set_src(ui_comp_get_child(ui_AppTitleComp4, UI_COMP_APPTITLECOMP_APPIMAGE2), &ui_img_laptop_png);

    lv_label_set_text(ui_comp_get_child(ui_AppTitleComp4, UI_COMP_APPTITLECOMP_APPLABEL2), "Laptop Control");

    ui_AppControls3 = lv_obj_create(ui_LaptopControl);
    lv_obj_set_width(ui_AppControls3, 189);
    lv_obj_set_height(ui_AppControls3, 118);
    lv_obj_set_x(ui_AppControls3, -1);
    lv_obj_set_y(ui_AppControls3, -36);
    lv_obj_set_align(ui_AppControls3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AppControls3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AppControls3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppControls3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LaptopLockPanel = lv_obj_create(ui_AppControls3);
    lv_obj_set_width(ui_LaptopLockPanel, 175);
    lv_obj_set_height(ui_LaptopLockPanel, 66);
    lv_obj_set_x(ui_LaptopLockPanel, -1);
    lv_obj_set_y(ui_LaptopLockPanel, -35);
    lv_obj_set_align(ui_LaptopLockPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LaptopLockPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LaptopLockPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LaptopLockPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LaptopLockPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaptopLockPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LaptopLockPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LaptopLockPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LockLaptopBtn = lv_btn_create(ui_LaptopLockPanel);
    lv_obj_set_width(ui_LockLaptopBtn, 84);
    lv_obj_set_height(ui_LockLaptopBtn, 48);
    lv_obj_set_x(ui_LockLaptopBtn, -15);
    lv_obj_set_y(ui_LockLaptopBtn, 10);
    lv_obj_set_align(ui_LockLaptopBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_LockLaptopBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_LockLaptopBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_LockLaptopBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LockLaptopBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LockLabel = lv_label_create(ui_LockLaptopBtn);
    lv_obj_set_width(ui_LockLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LockLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LockLabel, -7);
    lv_obj_set_y(ui_LockLabel, 7);
    lv_obj_set_align(ui_LockLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LockLabel, "Lock");

    lv_obj_add_event_cb(ui_LockLaptopBtn, ui_event_LockLaptopBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LaptopControl, ui_event_LaptopControl, LV_EVENT_ALL, NULL);

}
