// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_SettingsScreen, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsScreen, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    lv_obj_set_style_pad_left(ui_SettingsScreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsScreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsScreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsScreen, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_AppTitleComp3 = ui_AppTitleComp_create(ui_SettingsScreen);
    lv_obj_set_width(ui_AppTitleComp3, 159);
    lv_obj_set_height(ui_AppTitleComp3, 31);
    lv_obj_set_x(ui_AppTitleComp3, 0);
    lv_obj_set_y(ui_AppTitleComp3, -82);
    lv_obj_set_flex_flow(ui_AppTitleComp3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AppTitleComp3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_EVENLY);

    lv_img_set_src(ui_comp_get_child(ui_AppTitleComp3, UI_COMP_APPTITLECOMP_APPIMAGE2), &ui_img_settings_png);

    lv_label_set_text(ui_comp_get_child(ui_AppTitleComp3, UI_COMP_APPTITLECOMP_APPLABEL2), "Settings");

    ui_AppControls2 = lv_obj_create(ui_SettingsScreen);
    lv_obj_set_width(ui_AppControls2, 189);
    lv_obj_set_height(ui_AppControls2, 118);
    lv_obj_set_x(ui_AppControls2, -1);
    lv_obj_set_y(ui_AppControls2, -36);
    lv_obj_set_align(ui_AppControls2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AppControls2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AppControls2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AppControls2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectToWifiBtn = lv_btn_create(ui_AppControls2);
    lv_obj_set_width(ui_ConnectToWifiBtn, 160);
    lv_obj_set_height(ui_ConnectToWifiBtn, 27);
    lv_obj_set_align(ui_ConnectToWifiBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ConnectToWifiBtn, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ConnectToWifiBtn, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectToWifiBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConnectToWifiBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_ConnectToWifiBtn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect WiFi");

    ui_Image1 = lv_img_create(ui_ConnectToWifiBtn);
    lv_img_set_src(ui_Image1, &ui_img_wifi_connected_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 100);

    ui_AutoConnectPanel = lv_obj_create(ui_AppControls2);
    lv_obj_set_width(ui_AutoConnectPanel, 158);
    lv_obj_set_height(ui_AutoConnectPanel, 37);
    lv_obj_set_x(ui_AutoConnectPanel, -12);
    lv_obj_set_y(ui_AutoConnectPanel, 24);
    lv_obj_set_align(ui_AutoConnectPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AutoConnectPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AutoConnectPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AutoConnectPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AutoConnectLabel = lv_label_create(ui_AutoConnectPanel);
    lv_obj_set_width(ui_AutoConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AutoConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AutoConnectLabel, -31);
    lv_obj_set_y(ui_AutoConnectLabel, 11);
    lv_obj_set_align(ui_AutoConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AutoConnectLabel, "Auto Connect?");
    lv_obj_set_style_text_font(ui_AutoConnectLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_autoConnectSwitch = lv_switch_create(ui_AutoConnectPanel);
    lv_obj_set_width(ui_autoConnectSwitch, 39);
    lv_obj_set_height(ui_autoConnectSwitch, 20);
    lv_obj_set_x(ui_autoConnectSwitch, -5);
    lv_obj_set_y(ui_autoConnectSwitch, 45);
    lv_obj_set_align(ui_autoConnectSwitch, LV_ALIGN_CENTER);


    ui_ConnectionStatusLabel = lv_label_create(ui_SettingsScreen);
    lv_obj_set_width(ui_ConnectionStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectionStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectionStatusLabel, 22);
    lv_obj_set_y(ui_ConnectionStatusLabel, -14);
    lv_obj_set_align(ui_ConnectionStatusLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectionStatusLabel, "");

    lv_obj_add_event_cb(ui_ConnectToWifiBtn, ui_event_ConnectToWifiBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}
