// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"

void ui_comp_roundButton_create_hook(lv_obj_t * comp)
{
}

void ui_comp_AppComponent_create_hook(lv_obj_t * comp)
{
}

void ui_comp_AppTitleComp_create_hook(lv_obj_t * comp)
{
}
