// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"


// COMPONENT AppComponent

lv_obj_t * ui_AppComponent_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_AppComponent;
    cui_AppComponent = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_AppComponent, 100);
    lv_obj_set_height(cui_AppComponent, 96);
    lv_obj_set_x(cui_AppComponent, -336);
    lv_obj_set_y(cui_AppComponent, -159);
    lv_obj_set_align(cui_AppComponent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_AppComponent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_AppComponent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_AppComponent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(cui_AppComponent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_AppComponent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_AppComponent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_AppComponent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_AppComponent, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_AppComponent, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_AppImage;
    cui_AppImage = lv_img_create(cui_AppComponent);
    lv_img_set_src(cui_AppImage, &ui_img_laptop_png);
    lv_obj_set_width(cui_AppImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_AppImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_AppImage, -7);
    lv_obj_set_y(cui_AppImage, -4);
    lv_obj_set_align(cui_AppImage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_AppImage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_AppImage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(cui_AppImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_AppImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_AppLabel;
    cui_AppLabel = lv_label_create(cui_AppComponent);
    lv_obj_set_width(cui_AppLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_AppLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_AppLabel, -3);
    lv_obj_set_y(cui_AppLabel, 26);
    lv_obj_set_align(cui_AppLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_AppLabel, "Lap Control");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_APPCOMPONENT_NUM);
    children[UI_COMP_APPCOMPONENT_APPCOMPONENT] = cui_AppComponent;
    children[UI_COMP_APPCOMPONENT_APPIMAGE] = cui_AppImage;
    children[UI_COMP_APPCOMPONENT_APPLABEL] = cui_AppLabel;
    lv_obj_add_event_cb(cui_AppComponent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_AppComponent, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_AppComponent_create_hook(cui_AppComponent);
    return cui_AppComponent;
}

