// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#ifndef _UI_COMP_APPTITLECOMP_H
#define _UI_COMP_APPTITLECOMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT AppTitleComp
#define UI_COMP_APPTITLECOMP_APPTITLECOMP 0
#define UI_COMP_APPTITLECOMP_APPIMAGE2 1
#define UI_COMP_APPTITLECOMP_APPLABEL2 2
#define _UI_COMP_APPTITLECOMP_NUM 3
lv_obj_t * ui_AppTitleComp_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
