// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"


// COMPONENT roundButton

lv_obj_t * ui_roundButton_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_roundButton;
    cui_roundButton = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_roundButton, 50);
    lv_obj_set_height(cui_roundButton, 50);
    lv_obj_set_x(cui_roundButton, 0);
    lv_obj_set_y(cui_roundButton, 88);
    lv_obj_set_align(cui_roundButton, LV_ALIGN_CENTER);
    lv_obj_clear_flag(cui_roundButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_roundButton, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_roundButton, lv_color_hex(0x65D7ED), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_roundButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_roundButton, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_roundButtonText;
    cui_roundButtonText = lv_label_create(cui_roundButton);
    lv_obj_set_width(cui_roundButtonText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_roundButtonText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_roundButtonText, LV_ALIGN_CENTER);
    lv_label_set_text(cui_roundButtonText, "GO");
    lv_obj_set_style_text_color(cui_roundButtonText, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_roundButtonText, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_roundButtonText, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_ROUNDBUTTON_NUM);
    children[UI_COMP_ROUNDBUTTON_ROUNDBUTTON] = cui_roundButton;
    children[UI_COMP_ROUNDBUTTON_ROUNDBUTTONTEXT] = cui_roundButtonText;
    lv_obj_add_event_cb(cui_roundButton, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_roundButton, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_roundButton_create_hook(cui_roundButton);
    return cui_roundButton;
}

