// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#ifndef _UI_COMP_APPCOMPONENT_H
#define _UI_COMP_APPCOMPONENT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT AppComponent
#define UI_COMP_APPCOMPONENT_APPCOMPONENT 0
#define UI_COMP_APPCOMPONENT_APPIMAGE 1
#define UI_COMP_APPCOMPONENT_APPLABEL 2
#define _UI_COMP_APPCOMPONENT_NUM 3
lv_obj_t * ui_AppComponent_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
