// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#include "../ui.h"


// COMPONENT AppTitleComp

lv_obj_t * ui_AppTitleComp_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_AppTitleComp;
    cui_AppTitleComp = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_AppTitleComp, 141);
    lv_obj_set_height(cui_AppTitleComp, 31);
    lv_obj_set_x(cui_AppTitleComp, 0);
    lv_obj_set_y(cui_AppTitleComp, -79);
    lv_obj_set_align(cui_AppTitleComp, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_AppTitleComp, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_AppTitleComp, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_AppTitleComp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_set_style_pad_left(cui_AppTitleComp, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_AppTitleComp, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_AppTitleComp, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_AppTitleComp, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_AppTitleComp, 0, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_AppTitleComp, 10, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    lv_obj_t * cui_AppImage2;
    cui_AppImage2 = lv_img_create(cui_AppTitleComp);
    lv_img_set_src(cui_AppImage2, &ui_img_laptop_png);
    lv_obj_set_width(cui_AppImage2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_AppImage2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_AppImage2, -7);
    lv_obj_set_y(cui_AppImage2, -4);
    lv_obj_set_align(cui_AppImage2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_AppImage2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_AppImage2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(cui_AppImage2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_AppImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(cui_AppImage2, 100);
    lv_obj_set_style_bg_color(cui_AppImage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_AppImage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_AppLabel2;
    cui_AppLabel2 = lv_label_create(cui_AppTitleComp);
    lv_obj_set_width(cui_AppLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_AppLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_AppLabel2, -19);
    lv_obj_set_y(cui_AppLabel2, 26);
    lv_obj_set_align(cui_AppLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_AppLabel2, "Title Text");

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_APPTITLECOMP_NUM);
    children[UI_COMP_APPTITLECOMP_APPTITLECOMP] = cui_AppTitleComp;
    children[UI_COMP_APPTITLECOMP_APPIMAGE2] = cui_AppImage2;
    children[UI_COMP_APPTITLECOMP_APPLABEL2] = cui_AppLabel2;
    lv_obj_add_event_cb(cui_AppTitleComp, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_AppTitleComp, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_AppTitleComp_create_hook(cui_AppTitleComp);
    return cui_AppTitleComp;
}

