// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: knobOS

#ifndef _UI_COMP_ROUNDBUTTON_H
#define _UI_COMP_ROUNDBUTTON_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT roundButton
#define UI_COMP_ROUNDBUTTON_ROUNDBUTTON 0
#define UI_COMP_ROUNDBUTTON_ROUNDBUTTONTEXT 1
#define _UI_COMP_ROUNDBUTTON_NUM 2
lv_obj_t * ui_roundButton_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
