name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on Arduino CLI
      run: bash $GITHUB_WORKSPACE/build-arduino.sh
    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      with:
        files: |
          $HOME/Arduino/Release/Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
      
