name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build on Arduino CLI
      run: bash $GITHUB_WORKSPACE/build-arduino.sh
    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: Changelog
      env:
        REPO: ${{ github.repository }}
    - uses: actions/upload-artifact@v4
      with:
        name: Release
        path: $GITHUB_WORKSPACE/Release.zip

      
      
